application:
  input:
    mascot_dat:
    - bfabric@fgcz-s-018.uzh.ch://usr/local/mascot//data/20150914/F223985.dat
    - bfabric@fgcz-s-018.uzh.ch://usr/local/mascot//data/20150914/F223986.dat
    - bfabric@fgcz-s-018.uzh.ch://usr/local/mascot//data/20150914/F223984.dat
    - bfabric@fgcz-s-018.uzh.ch://usr/local/mascot//data/20150907/F223705.dat
  output:
  - bfabric@fgczdata.fgcz-net.unizh.ch:/srv/www/htdocs//p1000/bfabric/Proteomics/DIA_Assay_Library_Generator/2015/2015-10/2015-10-09//workunit_135899//205476.zip
  parameters:
    mascot_database_location: /usr/local/mascot/sequence/
    maxN: '6'
    minN: '5'
    mzError: '0.05'
  protocol: scp
job_configuration:
  executable: /usr/bin/python /scratch/wolski/generateSpecLibrary/fgcz_AssayLibraryGeneration.py
  external_job_id: 46592
  input:
    mascot_dat:
    - extract_id: 32650
      extract_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-extract.html?extractId=32650
      resource_id: 203909
      resource_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-resource.html?resourceId=203909
      sample_id: 26545
      sample_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-sample.html?sampleId=26545
    - extract_id: 32650
      extract_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-extract.html?extractId=32650
      resource_id: 203908
      resource_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-resource.html?resourceId=203908
      sample_id: 26545
      sample_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-sample.html?sampleId=26545
    - extract_id: 32650
      extract_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-extract.html?extractId=32650
      resource_id: 203907
      resource_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-resource.html?resourceId=203907
      sample_id: 26545
      sample_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-sample.html?sampleId=26545
    - extract_id: 33310
      extract_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-extract.html?extractId=33310
      resource_id: 203582
      resource_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-resource.html?resourceId=203582
      sample_id: 26407
      sample_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-sample.html?sampleId=26407
  output:
    protocol: scp
    resource_id: 205476
    ssh_args: -o StrictHostKeyChecking=no -c arcfour -2 -l bfabric -x
  stderr:
    protocol: file
    resource_id: 205477
    url: /home/bfabric/sgeworker/logs/workunitid-135899_resourceid-205476.err
  stdout:
    protocol: file
    resource_id: 205478
    url: /home/bfabric/sgeworker/logs/workunitid-135899_resourceid-205476.out
  workunit_id: 135899
  workunit_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-workunit.html?workunitId=135899

