application:
  input:
    mascot_dat:
    - bfabric@fgcz-s-018.uzh.ch://usr/local/mascot//data/20150828/F223245.dat
    - bfabric@fgcz-s-018.uzh.ch://usr/local/mascot//data/20150828/F223244.dat
    - bfabric@fgcz-s-018.uzh.ch://usr/local/mascot//data/20150828/F223237.dat
    - bfabric@fgcz-s-018.uzh.ch://usr/local/mascot//data/20150828/F223235.dat
    - bfabric@fgcz-s-018.uzh.ch://usr/local/mascot//data/20150828/F223249.dat
  output:
  - bfabric@fgczdata.fgcz-net.unizh.ch:/srv/www/htdocs//p1531/bfabric/Proteomics/DIA_Assay_Library_Generator/2015/2015-09/2015-09-21//workunit_135497//204439.zip
  parameters:
    mascot_database_location: /usr/local/mascot/sequence/
    maxN: '6'
    minN: '5'
    mzError: '0.8'
  protocol: scp
job_configuration:
  executable: /scratch/wolski/generateSpecLibrary/fgcz_AssayLibraryGeneration.py
  external_job_id: 46331
  input:
    mascot_dat:
    - extract_id: 32871
      extract_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-extract.html?extractId=32871
      resource_id: 203112
      resource_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-resource.html?resourceId=203112
      sample_id: 26750
      sample_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-sample.html?sampleId=26750
    - extract_id: 32871
      extract_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-extract.html?extractId=32871
      resource_id: 203111
      resource_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-resource.html?resourceId=203111
      sample_id: 26750
      sample_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-sample.html?sampleId=26750
    - extract_id: 32871
      extract_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-extract.html?extractId=32871
      resource_id: 203110
      resource_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-resource.html?resourceId=203110
      sample_id: 26750
      sample_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-sample.html?sampleId=26750
    - extract_id: 32871
      extract_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-extract.html?extractId=32871
      resource_id: 203109
      resource_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-resource.html?resourceId=203109
      sample_id: 26750
      sample_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-sample.html?sampleId=26750
    - extract_id: 32871
      extract_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-extract.html?extractId=32871
      resource_id: 203108
      resource_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-resource.html?resourceId=203108
      sample_id: 26750
      sample_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-sample.html?sampleId=26750
  output:
    protocol: scp
    resource_id: 204439
    ssh_args: -o StrictHostKeyChecking=no -c arcfour -2 -l bfabric -x
  stderr:
    protocol: file
    resource_id: 204440
    url: /home/bfabric/sgeworker/logs/workunitid-135497_resourceid-204439.err
  stdout:
    protocol: file
    resource_id: 204441
    url: /home/bfabric/sgeworker/logs/workunitid-135497_resourceid-204439.out
  workunit_id: 135497
  workunit_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-workunit.html?workunitId=135497

