application:
  input:
    mascot_dat:
    - bfabric@fgcz-s-018.uzh.ch://usr/local/mascot//data/20150914/F223983.dat
  output:
  - bfabric@fgczdata.fgcz-net.unizh.ch:/srv/www/htdocs//p1000/bfabric/Proteomics/DIA_Assay_Library_Generator/2015/2015-10/2015-10-08//workunit_135888//205448.zip
  parameters:
    mascot_database_location: /usr/local/mascot/sequence/
    maxN: '6'
    minN: '5'
    mzError: '0.05'
  protocol: scp
job_configuration:
  executable: /scratch/wolski/generateSpecLibrary/fgcz_test_yaml.py
  external_job_id: 46573
  input:
    mascot_dat:
    - extract_id: 32650
      extract_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-extract.html?extractId=32650
      resource_id: 203910
      resource_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-resource.html?resourceId=203910
      sample_id: 26545
      sample_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-sample.html?sampleId=26545
  output:
    protocol: scp
    resource_id: 205448
    ssh_args: -o StrictHostKeyChecking=no -c arcfour -2 -l bfabric -x
  stderr:
    protocol: file
    resource_id: 205449
    url: /home/bfabric/sgeworker/logs/workunitid-135888_resourceid-205448.err
  stdout:
    protocol: file
    resource_id: 205450
    url: /home/bfabric/sgeworker/logs/workunitid-135888_resourceid-205448.out
  workunit_id: 135888
  workunit_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-workunit.html?workunitId=135888

